var found = true;
var grade = 98.5;
var firstName = 'ram';
var secondName = 'krishna';
found = false;
grade = 100;
found = 100;
console.log(found);
console.log(grade);
console.log(firstName);
console.log("Hi ".concat(firstName, " ").concat(secondName));
